export const GET_PROPERTIES = 'GET_PROPERTIES';
export const GET_BUY_PROPERTIES = 'GET_BUY_PROPERTIES';
export const GET_RENT_PROPERTIES = 'GET_RENT_PROPERTIES';
export const GET_LOCATIONS = 'GET_LOCATIONS';

